on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Building
        run: |
          brew install automake
          make
          make debug-dmg
          shasum -a 256 build/Debug/GostX.dmg > build/Debug/GostX.dmg.checksum

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: GostX
          path: |
            build/Debug/GostX.dmg
            build/Debug/GostX.dmg.checksum
