on:
  push:
    branches:
      - '!main'

jobs:
  build:
    runs-on: macos-12
    steps:
      - use: actions/checkout@v3
        with:
          submodules: recursive

      - name: Make
        run: |
          make
