on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Make
        run: |
          echo 'Doing make'
          make
